version: "3.8"

services:
  ml-agents:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MLAGENTS_VERSION: ${MLAGENTS_VERSION}
        CUDA_VERSION: ${CUDA_VERSION:-11.8}
        USE_CUDA: ${USE_CUDA:-false}
    container_name: unity-env
    stdin_open: true
    tty: true
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - ./unity-project:/unity-project
    command: /bin/bash
